# Generated by Django 2.0 on 2018-11-26 14:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='sent_frome',
            new_name='sent_from',
        ),
        migrations.RemoveField(
            model_name='user',
            name='uname',
        ),
        migrations.AlterField(
            model_name='product',
            name='expired_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 26, 14, 16, 38, 831101)),
        ),
    ]
