# Generated by Django 2.0 on 2018-11-29 11:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20181126_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='productname',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='expired_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 29, 11, 31, 1, 177594)),
        ),
        migrations.AlterField(
            model_name='product',
            name='profile',
            field=models.FileField(upload_to='products'),
        ),
    ]
