# Generated by Django 2.0 on 2018-12-06 14:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20181206_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='expired_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 5, 22, 31, 0, 282657)),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile',
            field=models.FileField(blank=True, upload_to='profiles'),
        ),
    ]
