# Generated by Django 2.0 on 2018-12-28 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20181228_1119'),
        ('users', '0013_auto_20181228_1211'),
    ]

    operations = [
    ]
